### ISSUE TITLE
Allow for non-standard suffixes/filenames for languages

### ISSUE THREAD

**Issue by dshahbaz** [getgrit/gritql#485]
I have files that should be treated as python, but do not end in `.py`. I can't convince `grit` to respect the files and treat them as python with any option or config value that I've found. Instead, grit fails with:

```
ERROR (code: 410) - Skipped <mypath here> since it is not a python file
```

My workaround is hardlinking <mypath> to <mypath>.py, but it would be ideal to force grit to ignore the suffix, or to register alternative patterns as a file type using `grit.yaml`.

**Comment by morgante** [comment]
I think there's too immediate things we could do:

- Adjust [this logic](https://github.com/getgrit/gritql/blob/44e1536af813f62c5c48dedc781aed56e3089cc9/crates/cli/src/analyze.rs#L208-L218) so that if the path of the file is directly specified (vs. being discovered via traversal) we always attempt to parse it.
- Add an `--extensions` flag to override which extensions are parsed at runtime.

Happy to review a PR.

**Comment by morgante** [comment]
I think option #1 is best.

**Comment by Alex-ley-scrub** [comment]
/attempt #485 

@dshahbaz what is the suffix of the file out of curiosity if you don't mind sharing?

It's not "pyi" by any chance is it? Or another (semi) valid/standard python extension? .pyi - Stub file ([PEP 484](https://peps.python.org/pep-0484/#stub-files))

I only ask because if it is .pyi I believe they are a true subset of .py files (they're just interface files with function signatues and type hints but no implementations, instead just have `...` in the function bodies etc.) and should be able to be parsed just like a normal .py file.

@morgante should we consider to add "pyi" here (I've done that in this commit 2ca176a in case the answer is yes, otherwise can revert):

https://github.com/getgrit/gritql/blob/a1b312bdefed4982f7a96304b88577762f7edcf1/crates/language/src/target_language.rs#L290

https://github.com/getgrit/gritql/blob/a1b312bdefed4982f7a96304b88577762f7edcf1/crates/language/src/target_language.rs#L346

This is my minimal reproducible example (added as a test case in this commit 7fb636d):

These both fail for me using the released version of grit (with or without `--force`):
```
echo 'class MyClass(object): ...' > dummy.nopy
grit apply '`object` => ``' dummy.nopy --lang=python --force
# out: dummy.nopy: ERROR (code: 410) - Skipped dummy.nopy since it is not a python file
# out: Processed 2 files and found 0 matches
```
and
```
echo 'class MyClass(object): ...' > dummy.pyi
grit apply '`object` => ``' dummy.pyi --lang=python --force
# out: dummy.pyi: ERROR (code: 410) - Skipped dummy.pyi since it is not a python file
# out: Processed 2 files and found 0 matches
```

(as an aside the count of processed files seems to be doubled for the failed ones, which I also fixed in this commit 0f51e22)

see my PR attempt coming shortly

**Comment by morgante** [comment]
Adding `.pyi` seems reasonable, as well as fixing the overall problem.

**Comment by dshahbaz** [comment]
Thank you! I haven't tried this yet.

In my use case I was attempting to use bazel  `BUILD` files, which approximately python, at least in terms of syntax.
